eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-zuul

#路由功能配置
#以/api-a/ 开头的请求都转发给service-ribbon服务
#以/api-b/开头的请求都转发给service-feign服务
#eg: http://localhost:8766/api-a/hi?name=yang
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign



